#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header

# install nginx server
sudo apt update
sudo apt install -y nginx
# allw nginx traffic using uncomplicated firewal
sudo ufw allow 'Nginx HTTP'
# creating index page and set its content Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html
# this will create 404 page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
# configure nginx server
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html{
        internal;
        }
}" > default
# applying the configuration
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
