#!/usr/bin/env bash
# A script that displays:
# bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Best School for the other iterations

i=0
while ((i < 10))
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
