#!/usr/bin/env bash
# This script displays:
# content of the current directory In a list format
# Where only part of the name after the first dash is displayed

list=$(ls)
for i in $list
do
	echo "$i" | cut -d "-" -f2
done
