#!/usr/bin/env bash

cp /etc/hosts ~/Alex.Alx
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/Alex.Alx
sed -i 's/.*facebook.com//g' ~/Alex.Alx
sed -i '1 a 8.8.8.8 facebook.com' ~/Alex.Alx
p -f ~/Alex.Alx /etc/hosts
